apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cnj-monitoring-resources.fullname" . }}-pg
  labels:
    app.kubernetes.io/name: {{ include "cnj-monitoring-resources.name" . }}-pg
    helm.sh/chart: {{ include "cnj-monitoring-resources.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
data:
  postgres-password: {{ .Values.secret.adminPassword | b64enc }}
  user: {{ .Values.secret.connectionUser | b64enc }}
  password: {{ .Values.secret.connectionPassword | b64enc }}
